/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.example.model.User;

public class App {
    public static void main(String[] args) {
        User sameer = new User.Builder().name("sameer").email("sameer@gmail.com").age(21).build();
        System.out.println(sameer);
    }
}
