/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.example.observer.Investor;
import org.example.subject.Stock;

public class App {
    public static void main(String[] args) {
        Stock tcs = new Stock("tcs", 32);
        Investor sameer = new Investor("Sameer");
        Investor rahul = new Investor("Rahul");
        tcs.subscribe(sameer);
        tcs.subscribe(rahul);
        tcs.setPrice(34);
    }
}
