spring:
  datasource:
    url: jdbc:mariadb://localhost:3300/${VECTOR_DB_NAME}
    username: ${VECTOR_DB_USERNAME}
    password: ${VECTOR_DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

  ai:
    openai:
      api-key: ${OPENROUTER_API_KEY}
      base-url: https://openrouter.ai/api
      chat:
        options:
          model: openai/gpt-oss-20b:free
          temperature: 0.7

    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: always

    vectorstore:
      mariadb:
        initialize-schema: true
    mcp:
      client:
        stdio:
          servers-configuration: classpath:servers.json

app:
  weather:
    api-key: ${WEATHER_AP_KEY}

logging:
  level:
    org.springframework.ai.chat.client.advisor: DEBUG

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans"