/*
 * This source file was generated by the Gradle 'init' task
 */
package proxies;

import proxies.classes.Man;
import proxies.classes.Person;
import proxies.classes.PersonInvocationHandler;

import java.lang.reflect.Proxy;

public class App {
    public static void main(String[] args) {
        Man mohan = new Man("Mohan", 30, "Hyderabad", "Telangana");
        ClassLoader mohanClassLoader = mohan.getClass().getClassLoader();
        Class[] interfaces = mohan.getClass().getInterfaces();
        Person proxyMohan = (Person) Proxy.newProxyInstance(mohanClassLoader, interfaces, new PersonInvocationHandler(mohan));
        proxyMohan.introduce(mohan.getName());
        proxyMohan.sayAge(mohan.getAge());
        proxyMohan.sayWhereFrom(mohan.getCity(), mohan.getState());
    }
}
