/*
 * This source file was generated by the Gradle 'init' task
 */
package com.notification;

import com.notification.impl.EmailNotification;
import com.notification.impl.SmsNotification;
import com.notification.notification.Notification;
import com.notification.notification.NotificationFactory;
import com.notification.notification.NotificationType;

public class App {
    public static void main(String[] args) {
        Notification emailNotification = NotificationFactory.create(NotificationType.EMAIL);
        Notification smsNotification = NotificationFactory.create(NotificationType.SMS);
        Notification pushNotification = NotificationFactory.create(NotificationType.PUSH);
        Notification slackNotification = NotificationFactory.create(NotificationType.SLACK);
        Notification whatsappNotification = NotificationFactory.create(NotificationType.WHATSAPP);

        emailNotification.sendNotification("Sameer Purchase a book");
        smsNotification.sendNotification("Sameer Purchase a book");
        pushNotification.sendNotification("Sameer Purchase a book");
        slackNotification.sendNotification("Sameer Purchase a book");
        whatsappNotification.sendNotification("Sameer Purchase a book");
    }
}
