# DATABASE CONNECTION
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT:3306}/${MYSQL_DB:authservice}?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=${MYSQL_USERNAME}
spring.datasource.password=${MYSQL_PASSWORD}
# JPA/Hibernate
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
# SERVER
server.port=${SERVER_PORT:9898}
# KAFKA CONFIGURATION
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS}
# Producer Configuration
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.example.serializer.UserInfoSerializer
spring.kafka.producer.acks=${KAFKA_PRODUCER_ACKS:all}
spring.kafka.producer.retries=${KAFKA_PRODUCER_RETRIES:3}
# Topic Name
spring.kafka.topic.name=${KAFKA_TOPIC:auth-events}
# LOGGING - Only what you need
logging.level.root=INFO
logging.level.org.example=DEBUG
logging.level.org.apache.kafka.clients.producer=DEBUG