/*
 * This source file was generated by the Gradle 'init' task
 */
package org.products;

import org.products.config.properties.*;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.context.properties.EnableConfigurationProperties;
import org.springframework.cache.annotation.EnableCaching;

@SpringBootApplication
@EnableCaching
@EnableConfigurationProperties({
        AppProperties.class,
        PaginationProperties.class,
        ServiceProperties.class,
        JwtProperties.class,
        CorsProperties.class
})
public class App {
    public static void main(String[] args) {
        SpringApplication.run(App.class, args);
    }
}
