/*
 * This source file was generated by the Gradle 'init' task
 */
package org.products;

import io.swagger.v3.oas.annotations.OpenAPIDefinition;
import io.swagger.v3.oas.annotations.info.Info;
import org.products.config.properties.AppProperties;
import org.products.config.properties.PaginationProperties;
import org.products.config.properties.ServiceProperties;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.context.properties.EnableConfigurationProperties;

@SpringBootApplication
@EnableConfigurationProperties({
        AppProperties.class,
        PaginationProperties.class,
        ServiceProperties.class
})
@OpenAPIDefinition(
        info = @Info(
                title = "Product API",
                version = "1.0",
                description = "Product System APIs"
        )
)
public class App {
    public static void main(String[] args) {
        SpringApplication.run(App.class, args);
    }
}
