/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.example.config.ConfigManager;

public class App {
    public static void main(String[] args) {
        ConfigManager configManager1 = ConfigManager.getInstance();
        ConfigManager configManager2 = ConfigManager.getInstance();
        System.out.println(configManager1 == configManager2);
        System.out.println(configManager1.getDbUrl());
        System.out.println(configManager1.getDbUsername());
        System.out.println(configManager1.getDbPassword());
    }
}
