/*
 * This source file was generated by the Gradle 'init' task
 */
package org.taskmanager;

import org.taskmanager.cli.TaskCLI;
import org.taskmanager.service.TaskManager;
import org.taskmanager.service.TaskReminderService;

public class App {
    public static void main(String[] args) {
        System.out.println("[System] Initializing Core Task Registry Components...");
        TaskManager taskManager = new TaskManager();
        TaskReminderService taskReminderService = new TaskReminderService(taskManager);
        TaskCLI taskCLI = new TaskCLI(taskManager, taskReminderService);

        Runtime.getRuntime().addShutdownHook(new Thread(() -> {
            System.out.println("\n[Shutdown Hook] Warning: JVM termination signal intercepted.");
            System.out.println("[Shutdown Hook] Securing resources and shutting down background tasks...");
            taskReminderService.shutdown();
            System.out.println("[Shutdown Hook] Core context wiped safely. Process terminated.");
        }));

        System.out.println("[System] Booting Command Line Shell Environment...\n");
        taskCLI.start();
    }
}
