/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.example.tools.WeatherTool;
import org.example.utils.DataLoader;
import org.example.utils.DataTransformer;
import org.junit.jupiter.api.Test;
import org.springframework.ai.document.Document;
import org.springframework.ai.vectorstore.VectorStore;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;

import java.util.List;

@SpringBootTest
public class AppTest {
    @Autowired
    private DataLoader dataLoader;
    @Autowired
    private DataTransformer dataTransformer;
    @Autowired
    private VectorStore vectorStore;
    @Autowired
    private WeatherTool weatherTool;

    // @Test
    public void testDataLoaderJson() {
        var documents = dataLoader.loadDocumentsFromJson();
        var transformedData = dataTransformer.transform(documents);
        vectorStore.add(transformedData);
        System.out.println("Data Save Successfully");
    }

    // @Test
    public void testDataLoaderPDF() {
        List<Document> documents = dataLoader.loadDocumentsFromDPF();
        var transformedData = dataTransformer.transform(documents);
        vectorStore.add(transformedData);
        System.out.println("Data Save Successfully");
    }

    @Test
    public void testGetWeatherTest() {
        String hyderabad = weatherTool.getWeather("hyderabad");
        System.out.println(hyderabad);
    }
}
