spring.application.name=spring-security
spring.security.user.name=user
spring.security.user.password=root

server.servlet.session.cookie.same-site=strict
spring.datasource.url=jdbc:postgresql://localhost:5432/learn
spring.datasource.username=postgres
spring.datasource.password=0000