package org.example;/*
 * This source file was generated by the Gradle 'init' task
 */

import org.example.Bean.UserConfig;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.ApplicationContext;
import org.springframework.context.support.ClassPathXmlApplicationContext;

@SpringBootApplication
public class App {
    public static void main(String[] args) {
        // SpringApplication.run(App.class, args);
        ApplicationContext context = new ClassPathXmlApplicationContext("application.xml");
        UserConfig userConfigBrean = context.getBean("userConfigBean", UserConfig.class);

    }
}
