spring.application.name=spring-ai-learn
spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.base-url=https://openrouter.ai/api/v1
spring.ai.openai.chat.options.model=openai/gpt-oss-120b:free

#spring.ai.openai.chat.options.max-tokens=500
#spring.ai.openai.chat.options.temperature=0.7