services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    env_file:
      - .env.docker
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}

    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-p${DB_PASSWORD}" ]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: on-failure:5

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: on-failure:5

  product-catalog:
    image: product-catelog:1.0
    container_name: product-catelog
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
      - "8080:8080"
    env_file:
      - .env.docker

    environment:
      DB_HOST: mysql
      REDIS_HOST: redis
    restart: on-failure:5
    
volumes:
  mysql_data:
  redis_data: