/*
 * This source file was generated by the Gradle 'init' task
 */
package com.payment;

import com.payment.imp.CreditCardPayment;
import com.payment.imp.NetBankingPayment;
import com.payment.imp.UpiPayment;
import com.payment.service.PaymentService;
import com.payment.strategy.PaymentStrategy;

public class App {
    public static void main(String[] args) {
        PaymentService upi = new PaymentService(new UpiPayment());
        PaymentService card = new PaymentService(new CreditCardPayment());
        PaymentService netBanking = new PaymentService(new NetBankingPayment());
        upi.pay(500);
        card.pay(500);
        netBanking.pay(500);
    }
}
