spring.application.name=spring-data-rest

spring.datasource.url=jdbc:postgresql://ep-nameless-rice-amhoqxnb-pooler.c-5.us-east-1.aws.neon.tech/neondb?sslmode=require

spring.datasource.username=neondb_owner
spring.datasource.password=npg_TVMtyKN79EIm

spring.jpa.hibernate.ddl-auto=update
spring.datasource.hikari.auto-commit=false