name: Product Catalog CI

on:
  push:
    branches:
      - deployment

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: 07_spring/product_catelog

    steps:
      - name: checkcode code
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Give gradlew permission
        run: chmod +x gradlew

      - name: Run tests
        run: ./gradlew test